---
- hosts: all
  become: true
  vars:
    mariadb_pri_domain_name: "test.vagrant.local"
  roles:
    - role: ansible-etc-hosts
  tasks:
    - name: pre-reqs
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - libselinux-python
      when: >
        (ansible_os_family == "RedHat" and
        ansible_distribution == "Fedora")

    - name: pre-reqs
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - libselinux-python
      when: >
        (ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora")

- hosts: galera-cluster-nodes
  become: true
  vars:
#    galera_cluster_bind_address: "{{ ansible_eth1.ipv4.address }}" #'{{ ansible_enp0s8.ipv4.address }}'
    galera_cluster_bind_address: "{{ ansible_enp0s8.ipv4.address }}"
    mariadb_pri_domain_name: "test.vagrant.local"
    galera_enable_mysqd_exporter_monitoring: true
    mysqld_exporter_binary_local_dir: "/Users/val.rudi/Documents/devops/clustering/ansible-mariadb-galera-cluster/dist/mysqld_exporter-0.12.1.linux-amd64"
  roles:
    - role: ansible-mariadb-galera-cluster
  tasks:
